#include <string>
#include <iostream>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <ctime>
#include <unistd.h>
#include <cmath>
#include <fstream>
#include <map>
/*#include "field.h"
#include "cell.h"
#include "view.h"
#include "controller.h"
#include "player.h"
#include "mediator.h"
#include "change_field.h"
#include "change_player.h"
#include "event.h"
#include "blind_trap.h"
#include "eat_energy.h"
#include "recreate_field.h"
#include "off_walls.h"
#include "event_mediator.h"*/